CREATE TABLE `wp_wpb2d_processed_dbtables` (  `name` varchar(255) NOT NULL,  `count` int(11) NOT NULL DEFAULT '0',  UNIQUE KEY `name` (`name`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40000 ALTER TABLE `wp_wpb2d_processed_dbtables` DISABLE KEYS */;
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('header', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_bad_behavior', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_cntctfrm_field', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_commentmeta', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_comments', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_itsec_lockouts', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_itsec_log', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_itsec_temp', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_nf_objectmeta', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_nf_objects', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_nf_relationships', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_ninja_forms_fav_fields', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_ninja_forms_fields', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_options', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_postmeta', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_posts', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_terms', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_term_relationships', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_term_taxonomy', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_usermeta', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_users', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_wfBlockedIPLog', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_wfConfig', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_wfCrawlers', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_wfFileMods', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_wfHits', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_wfIssues', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_wfLeechers', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_wfLogins', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_wfScanners', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_wfStatus', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_wpb2d_excluded_files', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_wpb2d_options', '-1');
INSERT INTO `wp_wpb2d_processed_dbtables` VALUES('wp_wpb2d_processed_dbtables', '-1');
/*!40000 ALTER TABLE `wp_wpb2d_processed_dbtables` ENABLE KEYS */;
