CREATE TABLE `wp_nf_objectmeta` (  `id` bigint(20) NOT NULL AUTO_INCREMENT,  `object_id` bigint(20) NOT NULL,  `meta_key` varchar(255) NOT NULL,  `meta_value` longtext NOT NULL,  PRIMARY KEY (`id`)) ENGINE=MyISAM AUTO_INCREMENT=80 DEFAULT CHARSET=utf8;
/*!40000 ALTER TABLE `wp_nf_objectmeta` DISABLE KEYS */;
INSERT INTO `wp_nf_objectmeta` VALUES('1', '1', 'date_updated', '2015-05-30');
INSERT INTO `wp_nf_objectmeta` VALUES('2', '1', 'form_title', 'Contact Form');
INSERT INTO `wp_nf_objectmeta` VALUES('3', '1', 'show_title', '0');
INSERT INTO `wp_nf_objectmeta` VALUES('4', '1', 'save_subs', '1');
INSERT INTO `wp_nf_objectmeta` VALUES('5', '1', 'logged_in', '0');
INSERT INTO `wp_nf_objectmeta` VALUES('6', '1', 'append_page', '11');
INSERT INTO `wp_nf_objectmeta` VALUES('7', '1', 'ajax', '0');
INSERT INTO `wp_nf_objectmeta` VALUES('8', '1', 'clear_complete', '1');
INSERT INTO `wp_nf_objectmeta` VALUES('9', '1', 'hide_complete', '1');
INSERT INTO `wp_nf_objectmeta` VALUES('10', '1', 'success_msg', 'Your form has been successfully submitted.');
INSERT INTO `wp_nf_objectmeta` VALUES('11', '1', 'email_from', '');
INSERT INTO `wp_nf_objectmeta` VALUES('12', '1', 'email_type', 'html');
INSERT INTO `wp_nf_objectmeta` VALUES('13', '1', 'user_email_msg', 'Thank you so much for contacting us. We will get back to you shortly.');
INSERT INTO `wp_nf_objectmeta` VALUES('14', '1', 'user_email_fields', '0');
INSERT INTO `wp_nf_objectmeta` VALUES('15', '1', 'admin_email_msg', '');
INSERT INTO `wp_nf_objectmeta` VALUES('16', '1', 'admin_email_fields', '1');
INSERT INTO `wp_nf_objectmeta` VALUES('17', '1', 'admin_attach_csv', '0');
INSERT INTO `wp_nf_objectmeta` VALUES('18', '1', 'email_from_name', '');
INSERT INTO `wp_nf_objectmeta` VALUES('19', '2', 'date_updated', '2014-09-09');
INSERT INTO `wp_nf_objectmeta` VALUES('20', '2', 'active', '1');
INSERT INTO `wp_nf_objectmeta` VALUES('21', '2', 'name', 'Email User');
INSERT INTO `wp_nf_objectmeta` VALUES('22', '2', 'type', 'email');
INSERT INTO `wp_nf_objectmeta` VALUES('23', '2', 'email_format', 'html');
INSERT INTO `wp_nf_objectmeta` VALUES('24', '2', 'attach_csv', '1');
INSERT INTO `wp_nf_objectmeta` VALUES('25', '2', 'from_name', 'Maui Wellness Center');
INSERT INTO `wp_nf_objectmeta` VALUES('26', '2', 'from_address', 'bioniclove@gmail.com');
INSERT INTO `wp_nf_objectmeta` VALUES('27', '2', 'reply_to', '');
INSERT INTO `wp_nf_objectmeta` VALUES('28', '2', 'to', 'field_2');
INSERT INTO `wp_nf_objectmeta` VALUES('29', '2', 'cc', '');
INSERT INTO `wp_nf_objectmeta` VALUES('30', '2', 'bcc', '');
INSERT INTO `wp_nf_objectmeta` VALUES('31', '2', 'email_subject', 'Thanks for Contacting Maui Wellness Center!');
INSERT INTO `wp_nf_objectmeta` VALUES('32', '2', 'email_message', 'Thank you so much for contacting us.\r\n\r\nWe look forward to speaking with you and will get back to you shortly.');
INSERT INTO `wp_nf_objectmeta` VALUES('33', '2', 'redirect_url', '');
INSERT INTO `wp_nf_objectmeta` VALUES('34', '2', 'success_message_loc', 'ninja_forms_display_before_fields');
INSERT INTO `wp_nf_objectmeta` VALUES('35', '2', 'success_msg', '');
INSERT INTO `wp_nf_objectmeta` VALUES('36', '3', 'date_updated', '2014-09-09');
INSERT INTO `wp_nf_objectmeta` VALUES('37', '3', 'active', '1');
INSERT INTO `wp_nf_objectmeta` VALUES('38', '3', 'name', 'Success Message');
INSERT INTO `wp_nf_objectmeta` VALUES('39', '3', 'type', 'success_message');
INSERT INTO `wp_nf_objectmeta` VALUES('40', '3', 'email_format', 'html');
INSERT INTO `wp_nf_objectmeta` VALUES('41', '3', 'attach_csv', '0');
INSERT INTO `wp_nf_objectmeta` VALUES('42', '3', 'from_name', '');
INSERT INTO `wp_nf_objectmeta` VALUES('43', '3', 'from_address', '');
INSERT INTO `wp_nf_objectmeta` VALUES('44', '3', 'reply_to', '');
INSERT INTO `wp_nf_objectmeta` VALUES('45', '3', 'to', '');
INSERT INTO `wp_nf_objectmeta` VALUES('46', '3', 'cc', '');
INSERT INTO `wp_nf_objectmeta` VALUES('47', '3', 'bcc', '');
INSERT INTO `wp_nf_objectmeta` VALUES('48', '3', 'email_subject', '');
INSERT INTO `wp_nf_objectmeta` VALUES('49', '3', 'email_message', '');
INSERT INTO `wp_nf_objectmeta` VALUES('50', '3', 'redirect_url', '');
INSERT INTO `wp_nf_objectmeta` VALUES('51', '3', 'success_message_loc', 'ninja_forms_display_after_fields');
INSERT INTO `wp_nf_objectmeta` VALUES('52', '3', 'success_msg', 'Your form has been successfully submitted.');
INSERT INTO `wp_nf_objectmeta` VALUES('53', '3', 'text_message_number', '');
INSERT INTO `wp_nf_objectmeta` VALUES('54', '3', 'text_message_carrier', '0');
INSERT INTO `wp_nf_objectmeta` VALUES('55', '3', 'text_message_message', '');
INSERT INTO `wp_nf_objectmeta` VALUES('56', '4', 'date_updated', '2014-09-09');
INSERT INTO `wp_nf_objectmeta` VALUES('57', '4', 'active', '1');
INSERT INTO `wp_nf_objectmeta` VALUES('58', '4', 'name', 'Email Admin');
INSERT INTO `wp_nf_objectmeta` VALUES('59', '4', 'type', 'email');
INSERT INTO `wp_nf_objectmeta` VALUES('60', '4', 'email_format', 'html');
INSERT INTO `wp_nf_objectmeta` VALUES('61', '4', 'attach_csv', '1');
INSERT INTO `wp_nf_objectmeta` VALUES('62', '4', 'from_name', '');
INSERT INTO `wp_nf_objectmeta` VALUES('63', '4', 'from_address', '');
INSERT INTO `wp_nf_objectmeta` VALUES('64', '4', 'reply_to', 'field_2');
INSERT INTO `wp_nf_objectmeta` VALUES('65', '4', 'to', '');
INSERT INTO `wp_nf_objectmeta` VALUES('66', '4', 'cc', '');
INSERT INTO `wp_nf_objectmeta` VALUES('67', '4', 'bcc', '');
INSERT INTO `wp_nf_objectmeta` VALUES('68', '4', 'email_subject', 'Ninja Form Submission');
INSERT INTO `wp_nf_objectmeta` VALUES('69', '4', 'email_message', '[ninja_forms_all_fields]');
INSERT INTO `wp_nf_objectmeta` VALUES('70', '4', 'redirect_url', '');
INSERT INTO `wp_nf_objectmeta` VALUES('71', '4', 'success_message_loc', 'ninja_forms_display_before_fields');
INSERT INTO `wp_nf_objectmeta` VALUES('72', '4', 'success_msg', '');
INSERT INTO `wp_nf_objectmeta` VALUES('73', '4', 'text_message_number', '');
INSERT INTO `wp_nf_objectmeta` VALUES('74', '4', 'text_message_carrier', '0');
INSERT INTO `wp_nf_objectmeta` VALUES('75', '4', 'text_message_message', '');
INSERT INTO `wp_nf_objectmeta` VALUES('76', '1', 'not_logged_in_msg', '');
INSERT INTO `wp_nf_objectmeta` VALUES('77', '1', 'sub_limit_number', '');
INSERT INTO `wp_nf_objectmeta` VALUES('78', '1', 'sub_limit_msg', '');
INSERT INTO `wp_nf_objectmeta` VALUES('79', '1', 'last_sub', '105');
/*!40000 ALTER TABLE `wp_nf_objectmeta` ENABLE KEYS */;
