CREATE TABLE `wp_cntctfrm_field` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `name` char(100) NOT NULL,  UNIQUE KEY `id` (`id`)) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=latin1;
/*!40000 ALTER TABLE `wp_cntctfrm_field` DISABLE KEYS */;
INSERT INTO `wp_cntctfrm_field` VALUES('1', 'name');
INSERT INTO `wp_cntctfrm_field` VALUES('2', 'email');
INSERT INTO `wp_cntctfrm_field` VALUES('3', 'subject');
INSERT INTO `wp_cntctfrm_field` VALUES('4', 'message');
INSERT INTO `wp_cntctfrm_field` VALUES('5', 'address');
INSERT INTO `wp_cntctfrm_field` VALUES('6', 'phone');
INSERT INTO `wp_cntctfrm_field` VALUES('7', 'attachment');
INSERT INTO `wp_cntctfrm_field` VALUES('8', 'attachment_explanations');
INSERT INTO `wp_cntctfrm_field` VALUES('9', 'send_copy');
INSERT INTO `wp_cntctfrm_field` VALUES('10', 'sent_from');
INSERT INTO `wp_cntctfrm_field` VALUES('11', 'date_time');
INSERT INTO `wp_cntctfrm_field` VALUES('12', 'coming_from');
INSERT INTO `wp_cntctfrm_field` VALUES('13', 'user_agent');
/*!40000 ALTER TABLE `wp_cntctfrm_field` ENABLE KEYS */;
